[package]
name = "loop"
version = "0.1.0"
edition = "2018"

[dependencies]
strum_macros = "0.21.1"
strum = "0.21.0"
byteorder = "1.4.3"
rustyline = "9.0.0"
colored = "2"
sentry = "0.23.0"
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
dirs = "4.0.0"
chrono = "0.4.19"
